#!/bin/bash
set -e

echo "Cleaning permissions/autogenerated directory for ${plugin_dir}..."
if [ -d "permissions/autogenerated" ]; then
  rm -rf "permissions/autogenerated"
fi

# Run the tests to generate the TS bindings
cargo test
